Ipfs dockerize
DarkFlorist/lunaria pull request #231
Opened 2023-12-05 07:05 UTC by jubalm

2023-12-12 06:22 UTC, MicahZoltu requested changes

2023-12-12 06:22 UTC, MicahZoltu commented on Dockerfile
> +# Copy project files and run necessary symlinks npm needs
```suggestion
# Run the vendoring script
```

2023-12-12 06:22 UTC, MicahZoltu commented on Dockerfile
> +RUN printf '#!/bin/sh\nipfs add --cid-version 1 -r /export' >> /container-init.d/start.sh
This should match the Tornado hack.md.  We will probably need to install a couple CLI tools to make that work though, up on line ~24.

2023-12-14 11:01 UTC, MicahZoltu requested changes
Still need the fix in the Dockerfile, everything else looks fine though.

2023-12-14 11:01 UTC, MicahZoltu commented on Dockerfile
> +RUN printf '#!/bin/sh\nipfs add --cid-version 1 -r /export' >> /container-init.d/start.sh
This still needs to be addressed.  Ping me on Discord if you aren't sure how to do this.

2023-12-17 08:41 UTC, jubalm commented on .gitignore
> +vendor/index.js
removed from gitignore as it's handy to indeed check if the file is correctly removed by the vendor script

2023-12-21 11:25 UTC, MicahZoltu approved these changes

2023-12-26 04:24 UTC, merged